# Generated by Django 5.1.2 on 2024-10-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
